# Generated by Django 4.0.5 on 2022-09-28 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('product_description', models.TextField(blank=True, max_length=5000)),
                ('product_price', models.CharField(blank=True, max_length=20)),
                ('product_image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d')),
                ('product_create_time', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='products.categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Product_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_id', models.IntegerField(blank=True, default='')),
                ('user_id', models.IntegerField(blank=True, default='')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_wishlist',
            },
        ),
        migrations.CreateModel(
            name='Product_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kilometer', models.CharField(blank=True, default='29400', max_length=20)),
                ('product_fuel', models.CharField(blank=True, default='Gasoline', max_length=20)),
                ('product_cheaper', models.IntegerField(blank=True, default='125000000')),
                ('product_post_time', models.DateField(auto_now_add=True)),
                ('product_at', models.CharField(blank=True, default='AT', max_length=20)),
                ('product_auction_price', models.IntegerField(blank=True, default='326750000')),
                ('product_time_remaining', models.DateField(blank=True, default='')),
                ('product_condition', models.CharField(blank=True, default='Used', max_length=50)),
                ('product_color', models.CharField(blank=True, default='Gray', max_length=50)),
                ('product_reg_date', models.DateField(blank=True, default='')),
                ('product_body_type', models.CharField(blank=True, default='Hatchback', max_length=100)),
                ('product_manufacturing_year', models.IntegerField(blank=True, default='2018')),
                ('product_power', models.IntegerField(blank=True, default='182')),
                ('product_seats', models.IntegerField(blank=True, default='5')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
            options={
                'db_table': 'product_meta',
            },
        ),
        migrations.CreateModel(
            name='GalleryImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d')),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product')),
            ],
            options={
                'db_table': 'product_gallery',
            },
        ),
    ]
