# Generated by Django 4.0.5 on 2022-09-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=500)),
                ('product_content', models.IntegerField(max_length=5000)),
                ('product_create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('detail_title', models.CharField(max_length=5000)),
                ('detail_content', models.CharField(max_length=5000)),
                ('detail_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
