# Generated by Django 4.0.5 on 2022-09-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_details_detail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='', upload_to='uploads/%Y/%mm/%dd'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_content',
            field=models.CharField(max_length=5000),
        ),
    ]
