# Generated by Django 4.0.5 on 2022-09-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_jointablesmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointablesmodel',
            name='cat_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product_attributes',
            name='attribute_options',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('password', 'Password'), ('datetime-local', 'Date time')], default='', max_length=100),
        ),
    ]
