# Generated by Django 4.0.5 on 2022-09-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='detail_content',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='detail_title',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_content',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
