# Generated by Django 4.0.5 on 2022-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_jointablesmodel_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attributes',
            name='attribute_options',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('password', 'Password'), ('datetime-local', 'Date time')], max_length=100),
        ),
    ]
