# Generated by Django 4.0.5 on 2022-09-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_details_detail_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_content',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
