# Generated by Django 4.0.5 on 2022-09-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_attributes_attribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attribute_value',
            name='attribute_options',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('password', 'Password'), ('date', 'Date')], default='', max_length=100),
        ),
    ]
