# Generated by Django 4.0.5 on 2022-09-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_attribute_value_attribute_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_wishlist',
            name='prd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
