# Generated by Django 4.0.5 on 2022-09-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_details_detail_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='detail_content',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='detail_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_content',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
