# Generated by Django 4.0.5 on 2022-09-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_wishlist_prd_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_wishlist',
            old_name='prd_id',
            new_name='prd',
        ),
    ]
